### ISSUE TITLE
Guild configurations should be configurable via config.yml

### ISSUE THREAD

**Issue by VelvetToroyashi** [VelvetThePanda/Silk#189]
**Is your feature request related to a problem? Please describe.**
As it stands right now, Guild Configurations can only be changed in two ways: With sparse, half-baked commands, and directly modifying database values.

**Describe the solution you'd like**
While the dashboard is being developed, which is the superior way of going about this, a YAML file is both easy for general uses, and easy to work with programmatically.

**Describe alternatives you've considered**
INI Files *shudders*.

**Additional context**
An example config would be as such:

```yaml
config: # do not change the names.
  
  welcome:
    enabled: true
    greet_when: 
    greeting: "" # what to say when they've passed requisite verification. 
                 # substitutions: {@u} -> Mention the user {u} -> User's username {s} -> Server name
                 # Example: "Welcome to {s}, {@u}! We hope you enjoy your stay! 😄"
  
  moderation:
    mute_role: 0 # Id of the role 

    log:
      channel: 0 # the channel to log to for anything moderation-related
      edits: false
      deletions: false

    word_blacklist: # Words to blacklist. All messages will be scanned for these strings (case insensitive).
      enabled: false
      blacklist:
        - "Example 1"
        - "Exmaple 2"
    
    anti_invite: # block members from sending invites
      enabled: false # enable anti-invite
      delete_invites: false # whether to delete the message containing an invite
      scan_invites: false # whether to check if invites are valid. Good for servers without vanity urls
      warn_member: false # whether to warn members for sending non-whitelisted invites.
      anti_circumvention: false # false matches discord.gg/ true matches all discord-like invites and common circumventions to auto-mod
      allowed_invites:
        - "discord.gg/foo"
        - "discord.gg/bar"

```

Side note, I spent far too much time on this.
