### ISSUE TITLE
New Docker image for major overhaul to bot infrastructure.

### ISSUE THREAD

**Issue by VelvetThePanda** [VelvetThePanda/Silk#87]
Silk! No longer depends on JSON files scattered upon the filesystem, but now instead connects to an external, but locally ran database. 

```diff
- JSON Files

+ appSettings.json dependency file
```

**Comment by VelvetThePanda** [comment]
@NatsumiHB

**Comment by NatsumiHB** [comment]
Just mount the `appSettings.json` file as a docker volume and run the database in the same network

**Comment by NatsumiHB** [comment]
An example for your docker-compose would be this: ```yml
version: "3"

services:
  bot: VelvetThePanda/silk:latest
  volumes:
    - ./appSettings.json:/path/to/appSettings.json
  
  db:
    image: db-image # replace with db image name
    # additional settings for the db
```

In this case both services will automatically run in the same network (an internal one for that docker-compose file

**Comment by VelvetThePanda** [comment]
I literally dunno how to Docker, and probably never will tbf. @NatsumiHB You're good at docker, and we're making a web dash, and knowing you, you'll probably wanna containerize that too.

**Comment by CalebABG** [comment]
Took a stab at another example for the docker-compose file as well. I had to try to compose a docker-compose for another project I was working on and then never used it but still had the sample file. 

@NatsumiHB if you take a look, lemme know if I got anything wrong or out of place; Ty!! :) (also sorry if the indentation got messed up in the code block)

The addition is for the .Net UserSecrets file some may choose to use over the ```appSettings.json``` file. The docker image will copy over the folder with the given Secrets folder name (USER_SECRETS_ID) for the platform the container is running on. Default for the file is Windows, but the Mac/Linux is commented out below and can be un-commented.

```yml
version: "3"

services:
  bot:
    image: VelvetThePanda/silk:latest
    environment:
      - USER_SECRETS_ID=VelvetThePanda-SilkBot
    volumes:
      - ./appSettings.json:/path/to/appSettings.json
      # Net UserSecrets
      - ${APPDATA}/Microsoft/UserSecrets/$USER_SECRETS_ID:/root/.microsoft/usersecrets/$USER_SECRETS_ID # Windows
      #- ${HOME}/.microsoft/usersecrets/$USER_SECRETS_ID:/root/.microsoft/usersecrets/$USER_SECRETS_ID # Mac/Linux
  db:
    image: db-image # replace with db image name
```

**Comment by NatsumiHB** [comment]
@CalebABG looks good even tho for the db you will definitely need some more options depending on the database you're gonna use. Also make the bot depend on the db service so it starts before the bot (keep in mind that the bot is probably gonna crash when using PSQL since Postgres takes a while to load so you'd also need to add `restart: always` to the bot).
The rest looks decent.
 With my changes:
```yml
version: "3"

services:
  bot:
    image: VelvetThePanda/silk:latest
    restart: always
    depends_on:
      - db
    environment:
      - USER_SECRETS_ID=VelvetThePanda-SilkBot
    volumes:
      - ./appSettings.json:/path/to/appSettings.json
      # Net UserSecrets
      - ${APPDATA}/Microsoft/UserSecrets/$USER_SECRETS_ID:/root/.microsoft/usersecrets/$USER_SECRETS_ID # Windows
      #- ${HOME}/.microsoft/usersecrets/$USER_SECRETS_ID:/root/.microsoft/usersecrets/$USER_SECRETS_ID # Mac/Linux
  db:
    image: db-image # replace with db image name
    # additional settings
```

And for the webpanel @VelvetThePanda sure thing, just open an issue and assign me when needed.
